import numpy

einsum = numpy.einsum

def eom_ee_epccsd_1_s1_sigma_slow(RS, RD, R1, RS1, amps, F, I, w, g, h, G, H):
    T1,T2,S1,U11 = amps

    sigS = numpy.zeros(T1.shape)
    sigD = numpy.zeros(T2.shape)
    sig1 = numpy.zeros(S1.shape)
    sigS1 = numpy.zeros(U11.shape)

    sigS += -1.0*einsum('ji,aj->ai', F.oo, RS)
    sigS += 1.0*einsum('ab,bi->ai', F.vv, RS)
    sigS += 1.0*einsum('I,Iai->ai', G, RS1)
    sigS += 1.0*einsum('Iai,I->ai', g.vo, R1)
    sigS += -1.0*einsum('jb,abji->ai', F.ov, RD)
    sigS += -1.0*einsum('ajbi,bj->ai', I.vovo, RS)
    sigS += -1.0*einsum('Iji,Iaj->ai', g.oo, RS1)
    sigS += 1.0*einsum('Iab,Ibi->ai', g.vv, RS1)
    sigS += 0.5*einsum('jkib,abkj->ai', I.ooov, RD)
    sigS += 0.5*einsum('ajbc,cbji->ai', I.vovv, RD)
    sigS += -1.0*einsum('jb,bi,aj->ai', F.ov, T1, RS)
    sigS += -1.0*einsum('jb,aj,bi->ai', F.ov, T1, RS)
    sigS += -1.0*einsum('Iji,aj,I->ai', g.oo, T1, R1)
    sigS += -1.0*einsum('Iji,I,aj->ai', g.oo, S1, RS)
    sigS += 1.0*einsum('Iab,bi,I->ai', g.vv, T1, R1)
    sigS += 1.0*einsum('Iab,I,bi->ai', g.vv, S1, RS)
    sigS += -1.0*einsum('jkib,aj,bk->ai', I.ooov, T1, RS)
    sigS += 1.0*einsum('jkib,bj,ak->ai', I.ooov, T1, RS)
    sigS += -1.0*einsum('ajbc,ci,bj->ai', I.vovv, T1, RS)
    sigS += 1.0*einsum('ajbc,cj,bi->ai', I.vovv, T1, RS)
    sigS += -1.0*einsum('Ijb,bi,Iaj->ai', g.ov, T1, RS1)
    sigS += -1.0*einsum('Ijb,aj,Ibi->ai', g.ov, T1, RS1)
    sigS += 1.0*einsum('Ijb,bj,Iai->ai', g.ov, T1, RS1)
    sigS += -1.0*einsum('Ijb,abji,I->ai', g.ov, T2, R1)
    sigS += -1.0*einsum('Ijb,I,abji->ai', g.ov, S1, RD)
    sigS += 1.0*einsum('Ijb,Iai,bj->ai', g.ov, U11, RS)
    sigS += -1.0*einsum('Ijb,Ibi,aj->ai', g.ov, U11, RS)
    sigS += -1.0*einsum('Ijb,Iaj,bi->ai', g.ov, U11, RS)
    sigS += -0.5*einsum('jkbc,ci,abkj->ai', I.oovv, T1, RD)
    sigS += -0.5*einsum('jkbc,aj,cbki->ai', I.oovv, T1, RD)
    sigS += 1.0*einsum('jkbc,cj,abki->ai', I.oovv, T1, RD)
    sigS += 1.0*einsum('jkbc,acji,bk->ai', I.oovv, T2, RS)
    sigS += 0.5*einsum('jkbc,cbji,ak->ai', I.oovv, T2, RS)
    sigS += 0.5*einsum('jkbc,ackj,bi->ai', I.oovv, T2, RS)
    sigS += -1.0*einsum('Ijb,bi,aj,I->ai', g.ov, T1, T1, R1)
    sigS += -1.0*einsum('Ijb,bi,I,aj->ai', g.ov, T1, S1, RS)
    sigS += -1.0*einsum('Ijb,aj,I,bi->ai', g.ov, T1, S1, RS)
    sigS += 1.0*einsum('jkbc,ci,aj,bk->ai', I.oovv, T1, T1, RS)
    sigS += -1.0*einsum('jkbc,ci,bj,ak->ai', I.oovv, T1, T1, RS)
    sigS += -1.0*einsum('jkbc,aj,ck,bi->ai', I.oovv, T1, T1, RS)

    sigD += 1.0*einsum('ki,bakj->abij', F.oo, RD)
    sigD += -1.0*einsum('kj,baki->abij', F.oo, RD)
    sigD += -1.0*einsum('bc,acji->abij', F.vv, RD)
    sigD += 1.0*einsum('ac,bcji->abij', F.vv, RD)
    sigD += -1.0*einsum('bkji,ak->abij', I.vooo, RS)
    sigD += 1.0*einsum('akji,bk->abij', I.vooo, RS)
    sigD += 1.0*einsum('baci,cj->abij', I.vvvo, RS)
    sigD += -1.0*einsum('bacj,ci->abij', I.vvvo, RS)
    sigD += -1.0*einsum('Ibi,Iaj->abij', g.vo, RS1)
    sigD += 1.0*einsum('Iai,Ibj->abij', g.vo, RS1)
    sigD += 1.0*einsum('Ibj,Iai->abij', g.vo, RS1)
    sigD += -1.0*einsum('Iaj,Ibi->abij', g.vo, RS1)
    sigD += -0.5*einsum('klji,balk->abij', I.oooo, RD)
    sigD += -1.0*einsum('bkci,ackj->abij', I.vovo, RD)
    sigD += 1.0*einsum('akci,bckj->abij', I.vovo, RD)
    sigD += 1.0*einsum('bkcj,acki->abij', I.vovo, RD)
    sigD += -1.0*einsum('akcj,bcki->abij', I.vovo, RD)
    sigD += -0.5*einsum('bacd,dcji->abij', I.vvvv, RD)
    sigD += 1.0*einsum('kc,ci,bakj->abij', F.ov, T1, RD)
    sigD += -1.0*einsum('kc,cj,baki->abij', F.ov, T1, RD)
    sigD += 1.0*einsum('kc,bk,acji->abij', F.ov, T1, RD)
    sigD += -1.0*einsum('kc,ak,bcji->abij', F.ov, T1, RD)
    sigD += -1.0*einsum('kc,bcji,ak->abij', F.ov, T2, RS)
    sigD += 1.0*einsum('kc,acji,bk->abij', F.ov, T2, RS)
    sigD += -1.0*einsum('kc,baki,cj->abij', F.ov, T2, RS)
    sigD += 1.0*einsum('kc,bakj,ci->abij', F.ov, T2, RS)
    sigD += 1.0*einsum('klji,bk,al->abij', I.oooo, T1, RS)
    sigD += -1.0*einsum('klji,ak,bl->abij', I.oooo, T1, RS)
    sigD += -1.0*einsum('bkci,cj,ak->abij', I.vovo, T1, RS)
    sigD += 1.0*einsum('akci,cj,bk->abij', I.vovo, T1, RS)
    sigD += -1.0*einsum('bkci,ak,cj->abij', I.vovo, T1, RS)
    sigD += 1.0*einsum('akci,bk,cj->abij', I.vovo, T1, RS)
    sigD += 1.0*einsum('bkcj,ci,ak->abij', I.vovo, T1, RS)
    sigD += -1.0*einsum('akcj,ci,bk->abij', I.vovo, T1, RS)
    sigD += 1.0*einsum('bkcj,ak,ci->abij', I.vovo, T1, RS)
    sigD += -1.0*einsum('akcj,bk,ci->abij', I.vovo, T1, RS)
    sigD += 1.0*einsum('bacd,di,cj->abij', I.vvvv, T1, RS)
    sigD += -1.0*einsum('bacd,dj,ci->abij', I.vvvv, T1, RS)
    sigD += 1.0*einsum('Iki,bk,Iaj->abij', g.oo, T1, RS1)
    sigD += -1.0*einsum('Iki,ak,Ibj->abij', g.oo, T1, RS1)
    sigD += -1.0*einsum('Ikj,bk,Iai->abij', g.oo, T1, RS1)
    sigD += 1.0*einsum('Ikj,ak,Ibi->abij', g.oo, T1, RS1)
    sigD += 1.0*einsum('Iki,bakj,I->abij', g.oo, T2, R1)
    sigD += -1.0*einsum('Ikj,baki,I->abij', g.oo, T2, R1)
    sigD += 1.0*einsum('Iki,I,bakj->abij', g.oo, S1, RD)
    sigD += -1.0*einsum('Ikj,I,baki->abij', g.oo, S1, RD)
    sigD += -1.0*einsum('Iki,Ibj,ak->abij', g.oo, U11, RS)
    sigD += 1.0*einsum('Iki,Iaj,bk->abij', g.oo, U11, RS)
    sigD += 1.0*einsum('Ikj,Ibi,ak->abij', g.oo, U11, RS)
    sigD += -1.0*einsum('Ikj,Iai,bk->abij', g.oo, U11, RS)
    sigD += -1.0*einsum('Ibc,ci,Iaj->abij', g.vv, T1, RS1)
    sigD += 1.0*einsum('Iac,ci,Ibj->abij', g.vv, T1, RS1)
    sigD += 1.0*einsum('Ibc,cj,Iai->abij', g.vv, T1, RS1)
    sigD += -1.0*einsum('Iac,cj,Ibi->abij', g.vv, T1, RS1)
    sigD += -1.0*einsum('Ibc,acji,I->abij', g.vv, T2, R1)
    sigD += 1.0*einsum('Iac,bcji,I->abij', g.vv, T2, R1)
    sigD += -1.0*einsum('Ibc,I,acji->abij', g.vv, S1, RD)
    sigD += 1.0*einsum('Iac,I,bcji->abij', g.vv, S1, RD)
    sigD += 1.0*einsum('Ibc,Iai,cj->abij', g.vv, U11, RS)
    sigD += -1.0*einsum('Iac,Ibi,cj->abij', g.vv, U11, RS)
    sigD += -1.0*einsum('Ibc,Iaj,ci->abij', g.vv, U11, RS)
    sigD += 1.0*einsum('Iac,Ibj,ci->abij', g.vv, U11, RS)
    sigD += 0.5*einsum('klic,cj,balk->abij', I.ooov, T1, RD)
    sigD += -1.0*einsum('klic,bk,aclj->abij', I.ooov, T1, RD)
    sigD += 1.0*einsum('klic,ak,bclj->abij', I.ooov, T1, RD)
    sigD += -1.0*einsum('klic,ck,balj->abij', I.ooov, T1, RD)
    sigD += -0.5*einsum('kljc,ci,balk->abij', I.ooov, T1, RD)
    sigD += 1.0*einsum('kljc,bk,acli->abij', I.ooov, T1, RD)
    sigD += -1.0*einsum('kljc,ak,bcli->abij', I.ooov, T1, RD)
    sigD += 1.0*einsum('kljc,ck,bali->abij', I.ooov, T1, RD)
    sigD += 1.0*einsum('klic,bakj,cl->abij', I.ooov, T2, RS)
    sigD += -1.0*einsum('klic,bckj,al->abij', I.ooov, T2, RS)
    sigD += 1.0*einsum('klic,ackj,bl->abij', I.ooov, T2, RS)
    sigD += 0.5*einsum('klic,balk,cj->abij', I.ooov, T2, RS)
    sigD += -1.0*einsum('kljc,baki,cl->abij', I.ooov, T2, RS)
    sigD += 1.0*einsum('kljc,bcki,al->abij', I.ooov, T2, RS)
    sigD += -1.0*einsum('kljc,acki,bl->abij', I.ooov, T2, RS)
    sigD += -0.5*einsum('kljc,balk,ci->abij', I.ooov, T2, RS)
    sigD += -1.0*einsum('bkcd,di,ackj->abij', I.vovv, T1, RD)
    sigD += 1.0*einsum('akcd,di,bckj->abij', I.vovv, T1, RD)
    sigD += 1.0*einsum('bkcd,dj,acki->abij', I.vovv, T1, RD)
    sigD += -1.0*einsum('akcd,dj,bcki->abij', I.vovv, T1, RD)
    sigD += 0.5*einsum('bkcd,ak,dcji->abij', I.vovv, T1, RD)
    sigD += -1.0*einsum('bkcd,dk,acji->abij', I.vovv, T1, RD)
    sigD += -0.5*einsum('akcd,bk,dcji->abij', I.vovv, T1, RD)
    sigD += 1.0*einsum('akcd,dk,bcji->abij', I.vovv, T1, RD)
    sigD += 1.0*einsum('bkcd,adji,ck->abij', I.vovv, T2, RS)
    sigD += 0.5*einsum('bkcd,dcji,ak->abij', I.vovv, T2, RS)
    sigD += -1.0*einsum('akcd,bdji,ck->abij', I.vovv, T2, RS)
    sigD += -0.5*einsum('akcd,dcji,bk->abij', I.vovv, T2, RS)
    sigD += -1.0*einsum('bkcd,adki,cj->abij', I.vovv, T2, RS)
    sigD += 1.0*einsum('akcd,bdki,cj->abij', I.vovv, T2, RS)
    sigD += 1.0*einsum('bkcd,adkj,ci->abij', I.vovv, T2, RS)
    sigD += -1.0*einsum('akcd,bdkj,ci->abij', I.vovv, T2, RS)
    sigD += -1.0*einsum('Ikc,bcji,Iak->abij', g.ov, T2, RS1)
    sigD += 1.0*einsum('Ikc,acji,Ibk->abij', g.ov, T2, RS1)
    sigD += -1.0*einsum('Ikc,baki,Icj->abij', g.ov, T2, RS1)
    sigD += 1.0*einsum('Ikc,bcki,Iaj->abij', g.ov, T2, RS1)
    sigD += -1.0*einsum('Ikc,acki,Ibj->abij', g.ov, T2, RS1)
    sigD += 1.0*einsum('Ikc,bakj,Ici->abij', g.ov, T2, RS1)
    sigD += -1.0*einsum('Ikc,bckj,Iai->abij', g.ov, T2, RS1)
    sigD += 1.0*einsum('Ikc,ackj,Ibi->abij', g.ov, T2, RS1)
    sigD += 1.0*einsum('Ikc,Ibi,ackj->abij', g.ov, U11, RD)
    sigD += -1.0*einsum('Ikc,Iai,bckj->abij', g.ov, U11, RD)
    sigD += 1.0*einsum('Ikc,Ici,bakj->abij', g.ov, U11, RD)
    sigD += -1.0*einsum('Ikc,Ibj,acki->abij', g.ov, U11, RD)
    sigD += 1.0*einsum('Ikc,Iaj,bcki->abij', g.ov, U11, RD)
    sigD += -1.0*einsum('Ikc,Icj,baki->abij', g.ov, U11, RD)
    sigD += 1.0*einsum('Ikc,Ibk,acji->abij', g.ov, U11, RD)
    sigD += -1.0*einsum('Ikc,Iak,bcji->abij', g.ov, U11, RD)
    sigD += -0.5*einsum('klcd,bdji,aclk->abij', I.oovv, T2, RD)
    sigD += 0.5*einsum('klcd,adji,bclk->abij', I.oovv, T2, RD)
    sigD += 0.25*einsum('klcd,dcji,balk->abij', I.oovv, T2, RD)
    sigD += -0.5*einsum('klcd,baki,dclj->abij', I.oovv, T2, RD)
    sigD += 1.0*einsum('klcd,bdki,aclj->abij', I.oovv, T2, RD)
    sigD += -1.0*einsum('klcd,adki,bclj->abij', I.oovv, T2, RD)
    sigD += -0.5*einsum('klcd,dcki,balj->abij', I.oovv, T2, RD)
    sigD += 0.5*einsum('klcd,bakj,dcli->abij', I.oovv, T2, RD)
    sigD += -1.0*einsum('klcd,bdkj,acli->abij', I.oovv, T2, RD)
    sigD += 1.0*einsum('klcd,adkj,bcli->abij', I.oovv, T2, RD)
    sigD += 0.5*einsum('klcd,dckj,bali->abij', I.oovv, T2, RD)
    sigD += 0.25*einsum('klcd,balk,dcji->abij', I.oovv, T2, RD)
    sigD += -0.5*einsum('klcd,bdlk,acji->abij', I.oovv, T2, RD)
    sigD += 0.5*einsum('klcd,adlk,bcji->abij', I.oovv, T2, RD)
    sigD += -1.0*einsum('klic,cj,bk,al->abij', I.ooov, T1, T1, RS)
    sigD += 1.0*einsum('klic,cj,ak,bl->abij', I.ooov, T1, T1, RS)
    sigD += -1.0*einsum('klic,bk,al,cj->abij', I.ooov, T1, T1, RS)
    sigD += 1.0*einsum('kljc,ci,bk,al->abij', I.ooov, T1, T1, RS)
    sigD += -1.0*einsum('kljc,ci,ak,bl->abij', I.ooov, T1, T1, RS)
    sigD += 1.0*einsum('kljc,bk,al,ci->abij', I.ooov, T1, T1, RS)
    sigD += -1.0*einsum('bkcd,di,cj,ak->abij', I.vovv, T1, T1, RS)
    sigD += 1.0*einsum('akcd,di,cj,bk->abij', I.vovv, T1, T1, RS)
    sigD += -1.0*einsum('bkcd,di,ak,cj->abij', I.vovv, T1, T1, RS)
    sigD += 1.0*einsum('akcd,di,bk,cj->abij', I.vovv, T1, T1, RS)
    sigD += 1.0*einsum('bkcd,dj,ak,ci->abij', I.vovv, T1, T1, RS)
    sigD += -1.0*einsum('akcd,dj,bk,ci->abij', I.vovv, T1, T1, RS)
    sigD += 1.0*einsum('Ikc,ci,bk,Iaj->abij', g.ov, T1, T1, RS1)
    sigD += -1.0*einsum('Ikc,ci,ak,Ibj->abij', g.ov, T1, T1, RS1)
    sigD += -1.0*einsum('Ikc,cj,bk,Iai->abij', g.ov, T1, T1, RS1)
    sigD += 1.0*einsum('Ikc,cj,ak,Ibi->abij', g.ov, T1, T1, RS1)
    sigD += 1.0*einsum('Ikc,ci,bakj,I->abij', g.ov, T1, T2, R1)
    sigD += -1.0*einsum('Ikc,cj,baki,I->abij', g.ov, T1, T2, R1)
    sigD += 1.0*einsum('Ikc,bk,acji,I->abij', g.ov, T1, T2, R1)
    sigD += -1.0*einsum('Ikc,ak,bcji,I->abij', g.ov, T1, T2, R1)
    sigD += 1.0*einsum('Ikc,ci,I,bakj->abij', g.ov, T1, S1, RD)
    sigD += -1.0*einsum('Ikc,cj,I,baki->abij', g.ov, T1, S1, RD)
    sigD += 1.0*einsum('Ikc,bk,I,acji->abij', g.ov, T1, S1, RD)
    sigD += -1.0*einsum('Ikc,ak,I,bcji->abij', g.ov, T1, S1, RD)
    sigD += -1.0*einsum('Ikc,ci,Ibj,ak->abij', g.ov, T1, U11, RS)
    sigD += 1.0*einsum('Ikc,ci,Iaj,bk->abij', g.ov, T1, U11, RS)
    sigD += 1.0*einsum('Ikc,cj,Ibi,ak->abij', g.ov, T1, U11, RS)
    sigD += -1.0*einsum('Ikc,cj,Iai,bk->abij', g.ov, T1, U11, RS)
    sigD += -1.0*einsum('Ikc,bk,Iai,cj->abij', g.ov, T1, U11, RS)
    sigD += 1.0*einsum('Ikc,ak,Ibi,cj->abij', g.ov, T1, U11, RS)
    sigD += 1.0*einsum('Ikc,bk,Iaj,ci->abij', g.ov, T1, U11, RS)
    sigD += -1.0*einsum('Ikc,ak,Ibj,ci->abij', g.ov, T1, U11, RS)
    sigD += -1.0*einsum('Ikc,bcji,I,ak->abij', g.ov, T2, S1, RS)
    sigD += 1.0*einsum('Ikc,acji,I,bk->abij', g.ov, T2, S1, RS)
    sigD += -1.0*einsum('Ikc,baki,I,cj->abij', g.ov, T2, S1, RS)
    sigD += 1.0*einsum('Ikc,bakj,I,ci->abij', g.ov, T2, S1, RS)
    sigD += -0.5*einsum('klcd,di,cj,balk->abij', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('klcd,di,bk,aclj->abij', I.oovv, T1, T1, RD)
    sigD += -1.0*einsum('klcd,di,ak,bclj->abij', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('klcd,di,ck,balj->abij', I.oovv, T1, T1, RD)
    sigD += -1.0*einsum('klcd,dj,bk,acli->abij', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('klcd,dj,ak,bcli->abij', I.oovv, T1, T1, RD)
    sigD += -1.0*einsum('klcd,dj,ck,bali->abij', I.oovv, T1, T1, RD)
    sigD += -0.5*einsum('klcd,bk,al,dcji->abij', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('klcd,bk,dl,acji->abij', I.oovv, T1, T1, RD)
    sigD += -1.0*einsum('klcd,ak,dl,bcji->abij', I.oovv, T1, T1, RD)
    sigD += -1.0*einsum('klcd,di,bakj,cl->abij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klcd,di,bckj,al->abij', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('klcd,di,ackj,bl->abij', I.oovv, T1, T2, RS)
    sigD += -0.5*einsum('klcd,di,balk,cj->abij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klcd,dj,baki,cl->abij', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('klcd,dj,bcki,al->abij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klcd,dj,acki,bl->abij', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('klcd,bk,adji,cl->abij', I.oovv, T1, T2, RS)
    sigD += -0.5*einsum('klcd,bk,dcji,al->abij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klcd,ak,bdji,cl->abij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klcd,dk,bcji,al->abij', I.oovv, T1, T2, RS)
    sigD += 0.5*einsum('klcd,ak,dcji,bl->abij', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('klcd,dk,acji,bl->abij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klcd,bk,adli,cj->abij', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('klcd,ak,bdli,cj->abij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klcd,dk,bali,cj->abij', I.oovv, T1, T2, RS)
    sigD += 0.5*einsum('klcd,dj,balk,ci->abij', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('klcd,bk,adlj,ci->abij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klcd,ak,bdlj,ci->abij', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('klcd,dk,balj,ci->abij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klcd,di,cj,bk,al->abij', I.oovv, T1, T1, T1, RS)
    sigD += -1.0*einsum('klcd,di,cj,ak,bl->abij', I.oovv, T1, T1, T1, RS)
    sigD += 1.0*einsum('klcd,di,bk,al,cj->abij', I.oovv, T1, T1, T1, RS)
    sigD += -1.0*einsum('klcd,dj,bk,al,ci->abij', I.oovv, T1, T1, T1, RS)

    sig1 += 1.0*einsum('I,I->I', w, R1)
    sig1 += 1.0*einsum('ia,Iai->I', F.ov, RS1)
    sig1 += 1.0*einsum('Iia,ai->I', h.ov, RS)
    sig1 += 1.0*einsum('Jia,J,Iai->I', g.ov, S1, RS1)
    sig1 += 1.0*einsum('Jia,Iai,J->I', g.ov, U11, R1)
    sig1 += -1.0*einsum('ijab,bi,Iaj->I', I.oovv, T1, RS1)
    sig1 += -1.0*einsum('ijab,Ibi,aj->I', I.oovv, U11, RS)

    sigS1 += -1.0*einsum('ji,Iaj->Iai', F.oo, RS1)
    sigS1 += 1.0*einsum('ab,Ibi->Iai', F.vv, RS1)
    sigS1 += 1.0*einsum('I,Iai->Iai', w, RS1)
    sigS1 += -1.0*einsum('Iji,aj->Iai', h.oo, RS)
    sigS1 += 1.0*einsum('Iab,bi->Iai', h.vv, RS)
    sigS1 += -1.0*einsum('ajbi,Ibj->Iai', I.vovo, RS1)
    sigS1 += -1.0*einsum('Ijb,abji->Iai', h.ov, RD)
    sigS1 += -1.0*einsum('jb,bi,Iaj->Iai', F.ov, T1, RS1)
    sigS1 += -1.0*einsum('jb,aj,Ibi->Iai', F.ov, T1, RS1)
    sigS1 += -1.0*einsum('jb,Ibi,aj->Iai', F.ov, U11, RS)
    sigS1 += -1.0*einsum('jb,Iaj,bi->Iai', F.ov, U11, RS)
    sigS1 += -1.0*einsum('Jji,J,Iaj->Iai', g.oo, S1, RS1)
    sigS1 += -1.0*einsum('Jji,Iaj,J->Iai', g.oo, U11, R1)
    sigS1 += -1.0*einsum('Ijb,bi,aj->Iai', h.ov, T1, RS)
    sigS1 += -1.0*einsum('Ijb,aj,bi->Iai', h.ov, T1, RS)
    sigS1 += 1.0*einsum('Jab,J,Ibi->Iai', g.vv, S1, RS1)
    sigS1 += 1.0*einsum('Jab,Ibi,J->Iai', g.vv, U11, R1)
    sigS1 += -1.0*einsum('jkib,aj,Ibk->Iai', I.ooov, T1, RS1)
    sigS1 += 1.0*einsum('jkib,bj,Iak->Iai', I.ooov, T1, RS1)
    sigS1 += -1.0*einsum('jkib,Iaj,bk->Iai', I.ooov, U11, RS)
    sigS1 += 1.0*einsum('jkib,Ibj,ak->Iai', I.ooov, U11, RS)
    sigS1 += -1.0*einsum('ajbc,ci,Ibj->Iai', I.vovv, T1, RS1)
    sigS1 += 1.0*einsum('ajbc,cj,Ibi->Iai', I.vovv, T1, RS1)
    sigS1 += -1.0*einsum('ajbc,Ici,bj->Iai', I.vovv, U11, RS)
    sigS1 += 1.0*einsum('ajbc,Icj,bi->Iai', I.vovv, U11, RS)
    sigS1 += -1.0*einsum('Jjb,Ibi,Jaj->Iai', g.ov, U11, RS1)
    sigS1 += -1.0*einsum('Jjb,Iaj,Jbi->Iai', g.ov, U11, RS1)
    sigS1 += 1.0*einsum('Jjb,Ibj,Jai->Iai', g.ov, U11, RS1)
    sigS1 += 1.0*einsum('Jjb,Jai,Ibj->Iai', g.ov, U11, RS1)
    sigS1 += -1.0*einsum('Jjb,Jbi,Iaj->Iai', g.ov, U11, RS1)
    sigS1 += -1.0*einsum('Jjb,Jaj,Ibi->Iai', g.ov, U11, RS1)
    sigS1 += 1.0*einsum('jkbc,acji,Ibk->Iai', I.oovv, T2, RS1)
    sigS1 += 0.5*einsum('jkbc,cbji,Iak->Iai', I.oovv, T2, RS1)
    sigS1 += 0.5*einsum('jkbc,ackj,Ibi->Iai', I.oovv, T2, RS1)
    sigS1 += -0.5*einsum('jkbc,Ici,abkj->Iai', I.oovv, U11, RD)
    sigS1 += -0.5*einsum('jkbc,Iaj,cbki->Iai', I.oovv, U11, RD)
    sigS1 += 1.0*einsum('jkbc,Icj,abki->Iai', I.oovv, U11, RD)
    sigS1 += -1.0*einsum('Jjb,bi,J,Iaj->Iai', g.ov, T1, S1, RS1)
    sigS1 += -1.0*einsum('Jjb,aj,J,Ibi->Iai', g.ov, T1, S1, RS1)
    sigS1 += -1.0*einsum('Jjb,bi,Iaj,J->Iai', g.ov, T1, U11, R1)
    sigS1 += -1.0*einsum('Jjb,aj,Ibi,J->Iai', g.ov, T1, U11, R1)
    sigS1 += -1.0*einsum('Jjb,J,Ibi,aj->Iai', g.ov, S1, U11, RS)
    sigS1 += -1.0*einsum('Jjb,J,Iaj,bi->Iai', g.ov, S1, U11, RS)
    sigS1 += 1.0*einsum('jkbc,ci,aj,Ibk->Iai', I.oovv, T1, T1, RS1)
    sigS1 += -1.0*einsum('jkbc,ci,bj,Iak->Iai', I.oovv, T1, T1, RS1)
    sigS1 += -1.0*einsum('jkbc,aj,ck,Ibi->Iai', I.oovv, T1, T1, RS1)
    sigS1 += 1.0*einsum('jkbc,ci,Iaj,bk->Iai', I.oovv, T1, U11, RS)
    sigS1 += -1.0*einsum('jkbc,ci,Ibj,ak->Iai', I.oovv, T1, U11, RS)
    sigS1 += 1.0*einsum('jkbc,aj,Ici,bk->Iai', I.oovv, T1, U11, RS)
    sigS1 += 1.0*einsum('jkbc,cj,Ibi,ak->Iai', I.oovv, T1, U11, RS)
    sigS1 += -1.0*einsum('jkbc,aj,Ick,bi->Iai', I.oovv, T1, U11, RS)
    sigS1 += 1.0*einsum('jkbc,cj,Iak,bi->Iai', I.oovv, T1, U11, RS)

    return sigS, sigD, sig1, sigS1

def eom_ee_epccsd_1_s1_sigma_int(RS, RD, R1, RS1, amps, F, I, w, g, h, G, H):
    T1,T2,S1,U11 = amps

    nm,nv,no = U11.shape
    Wov = numpy.zeros((no,nv))
    Wov += 1.0*einsum('ia->ia', F.ov)
    Wov += 1.0*einsum('I,Iia->ia', S1, g.ov)
    Wov += -1.0*einsum('bj,jiab->ia', T1, I.oovv)

    Wvv = numpy.zeros((nv,nv))
    Wvv += 1.0*einsum('ab->ab', F.vv)
    Wvv += -1.0*einsum('ai,ib->ab', T1, F.ov)
    Wvv += 1.0*einsum('I,Iab->ab', S1, g.vv)
    Wvv += 1.0*einsum('ci,aibc->ab', T1, I.vovv)
    Wvv += -1.0*einsum('Iai,Iib->ab', U11, g.ov)
    Wvv += 0.5*einsum('acij,jibc->ab', T2, I.oovv)
    Wvv += -1.0*einsum('ai,I,Iib->ab', T1, S1, g.ov)
    Wvv += -1.0*einsum('ai,cj,ijbc->ab', T1, T1, I.oovv)

    Woo = numpy.zeros((no,no))
    Woo += 1.0*einsum('ij->ij', F.oo)
    Woo += 1.0*einsum('aj,ia->ij', T1, F.ov)
    Woo += 1.0*einsum('I,Iij->ij', S1, g.oo)
    Woo += -1.0*einsum('ak,kija->ij', T1, I.ooov)
    Woo += 1.0*einsum('Iaj,Iia->ij', U11, g.ov)
    Woo += -0.5*einsum('abkj,kiba->ij', T2, I.oovv)
    Woo += 1.0*einsum('aj,I,Iia->ij', T1, S1, g.ov)
    Woo += 1.0*einsum('aj,bk,kiba->ij', T1, T1, I.oovv)

    Woovv = numpy.zeros((no,no,nv,nv))
    Woovv += 1.0*einsum('jiba->ijab', I.oovv)

    Wvovv = numpy.zeros((nv,no,nv,nv))
    Wvovv += -1.0*einsum('aicb->aibc', I.vovv)
    Wvovv += 1.0*einsum('aj,jicb->aibc', T1, I.oovv)

    Wooov = numpy.zeros((no,no,no,nv))
    Wooov += -1.0*einsum('jika->ijka', I.ooov)
    Wooov += 1.0*einsum('bk,jiab->ijka', T1, I.oovv)

    Wvvvv = numpy.zeros((nv,nv,nv,nv))
    Wvvvv += 1.0*einsum('badc->abcd', I.vvvv)
    Wvvvv += -1.0*einsum('ai,bidc->abcd', T1, I.vovv)
    Wvvvv += 1.0*einsum('bi,aidc->abcd', T1, I.vovv)
    Wvvvv += -0.5*einsum('baij,jidc->abcd', T2, I.oovv)
    Wvvvv += 1.0*einsum('bi,aj,ijdc->abcd', T1, T1, I.oovv)

    Woooo = numpy.zeros((no,no,no,no))
    Woooo += 1.0*einsum('jilk->ijkl', I.oooo)
    Woooo += -1.0*einsum('al,jika->ijkl', T1, I.ooov)
    Woooo += 1.0*einsum('ak,jila->ijkl', T1, I.ooov)
    Woooo += -0.5*einsum('ablk,jiba->ijkl', T2, I.oovv)
    Woooo += 1.0*einsum('ak,bl,jiba->ijkl', T1, T1, I.oovv)

    Wvoov = numpy.zeros((nv,no,no,nv))
    Wvoov += -1.0*einsum('aibj->aijb', I.vovo)
    Wvoov += -1.0*einsum('ak,kijb->aijb', T1, I.ooov)
    Wvoov += -1.0*einsum('cj,aibc->aijb', T1, I.vovv)
    Wvoov += 1.0*einsum('Iaj,Iib->aijb', U11, g.ov)
    Wvoov += 1.0*einsum('ackj,kibc->aijb', T2, I.oovv)
    Wvoov += 1.0*einsum('cj,ak,kibc->aijb', T1, T1, I.oovv)

    Wvvvo = numpy.zeros((nv,nv,nv,no))
    Wvvvo += -1.0*einsum('baci->abci', I.vvvo)
    Wvvvo += 1.0*einsum('baji,jc->abci', T2, F.ov)
    Wvvvo += 1.0*einsum('aj,bjci->abci', T1, I.vovo)
    Wvvvo += -1.0*einsum('bj,ajci->abci', T1, I.vovo)
    Wvvvo += -1.0*einsum('di,bacd->abci', T1, I.vvvv)
    Wvvvo += -1.0*einsum('Iai,Ibc->abci', U11, g.vv)
    Wvvvo += 1.0*einsum('Ibi,Iac->abci', U11, g.vv)
    Wvvvo += -0.5*einsum('bajk,kjic->abci', T2, I.ooov)
    Wvvvo += 1.0*einsum('adji,bjcd->abci', T2, I.vovv)
    Wvvvo += -1.0*einsum('bdji,ajcd->abci', T2, I.vovv)
    Wvvvo += 1.0*einsum('bj,ak,jkic->abci', T1, T1, I.ooov)
    Wvvvo += 1.0*einsum('di,aj,bjcd->abci', T1, T1, I.vovv)
    Wvvvo += -1.0*einsum('di,bj,ajcd->abci', T1, T1, I.vovv)
    Wvvvo += 1.0*einsum('bj,Iai,Ijc->abci', T1, U11, g.ov)
    Wvvvo += -1.0*einsum('aj,Ibi,Ijc->abci', T1, U11, g.ov)
    Wvvvo += 1.0*einsum('baji,I,Ijc->abci', T2, S1, g.ov)
    Wvvvo += 0.5*einsum('di,bajk,kjcd->abci', T1, T2, I.oovv)
    Wvvvo += -1.0*einsum('bj,adki,jkcd->abci', T1, T2, I.oovv)
    Wvvvo += 1.0*einsum('aj,bdki,jkcd->abci', T1, T2, I.oovv)
    Wvvvo += -1.0*einsum('dj,baki,jkcd->abci', T1, T2, I.oovv)
    Wvvvo += -1.0*einsum('di,bj,ak,jkcd->abci', T1, T1, T1, I.oovv)

    Wovoo = numpy.zeros((no,nv,no,no))
    Wovoo += 1.0*einsum('aikj->iajk', I.vooo)
    Wovoo += 1.0*einsum('abkj,ib->iajk', T2, F.ov)
    Wovoo += -1.0*einsum('al,likj->iajk', T1, I.oooo)
    Wovoo += 1.0*einsum('bk,aibj->iajk', T1, I.vovo)
    Wovoo += -1.0*einsum('bj,aibk->iajk', T1, I.vovo)
    Wovoo += 1.0*einsum('Iak,Iij->iajk', U11, g.oo)
    Wovoo += -1.0*einsum('Iaj,Iik->iajk', U11, g.oo)
    Wovoo += 1.0*einsum('ablk,lijb->iajk', T2, I.ooov)
    Wovoo += -1.0*einsum('ablj,likb->iajk', T2, I.ooov)
    Wovoo += -0.5*einsum('bckj,aicb->iajk', T2, I.vovv)
    Wovoo += 1.0*einsum('bk,al,lijb->iajk', T1, T1, I.ooov)
    Wovoo += -1.0*einsum('bj,al,likb->iajk', T1, T1, I.ooov)
    Wovoo += 1.0*einsum('bj,ck,aicb->iajk', T1, T1, I.vovv)
    Wovoo += 1.0*einsum('bj,Iak,Iib->iajk', T1, U11, g.ov)
    Wovoo += -1.0*einsum('bk,Iaj,Iib->iajk', T1, U11, g.ov)
    Wovoo += 1.0*einsum('abkj,I,Iib->iajk', T2, S1, g.ov)
    Wovoo += -1.0*einsum('bj,aclk,licb->iajk', T1, T2, I.oovv)
    Wovoo += 1.0*einsum('bk,aclj,licb->iajk', T1, T2, I.oovv)
    Wovoo += 0.5*einsum('al,bckj,licb->iajk', T1, T2, I.oovv)
    Wovoo += -1.0*einsum('bl,ackj,licb->iajk', T1, T2, I.oovv)
    Wovoo += -1.0*einsum('bj,ck,al,licb->iajk', T1, T1, T1, I.oovv)

    Wvovvvo = numpy.zeros((nv,no,nv,nv,nv,no))
    Wvovvvo += -1.0*einsum('bakj,kidc->aibcdj', T2, I.oovv)

    Woovovo = numpy.zeros((no,no,nv,no,nv,no))
    Woovovo += 1.0*einsum('aclk,jibc->ijakbl', T2, I.oovv)

    Wovvvoo = numpy.zeros((no,nv,nv,nv,no,no))
    Wovvvoo += 1.0*einsum('balk,lijc->iabcjk', T2, I.ooov)
    Wovvvoo += -1.0*einsum('balj,likc->iabcjk', T2, I.ooov)
    Wovvvoo += 1.0*einsum('adkj,bicd->iabcjk', T2, I.vovv)
    Wovvvoo += -1.0*einsum('bdkj,aicd->iabcjk', T2, I.vovv)
    Wovvvoo += -1.0*einsum('dj,balk,licd->iabcjk', T1, T2, I.oovv)
    Wovvvoo += 1.0*einsum('dk,balj,licd->iabcjk', T1, T2, I.oovv)
    Wovvvoo += -1.0*einsum('bl,adkj,licd->iabcjk', T1, T2, I.oovv)
    Wovvvoo += 1.0*einsum('al,bdkj,licd->iabcjk', T1, T2, I.oovv)

    Wp = numpy.zeros((nm))
    Wp += 1.0*einsum('I->I', G)
    Wp += 1.0*einsum('ai,Iia->I', T1, g.ov)

    Wp_p = numpy.zeros((nm,nm))
    Wp_p += numpy.diag(w)
    Wp_p += 1.0*einsum('Iai,Jia->IJ', U11, g.ov)

    Wpov = numpy.zeros((nm,no,nv))
    Wpov += 1.0*einsum('Iia->Iia', g.ov)

    Wpvv = numpy.zeros((nm,nv,nv))
    Wpvv += 1.0*einsum('Iab->Iab', g.vv)
    Wpvv += -1.0*einsum('ai,Iib->Iab', T1, g.ov)

    Wpoo = numpy.zeros((nm,no,no))
    Wpoo += 1.0*einsum('Iji->Iji', g.oo)
    Wpoo += 1.0*einsum('ai,Ija->Iji', T1, g.ov)

    Wpvo = numpy.zeros((nm,nv,no))
    Wpvo += 1.0*einsum('Iai->Iai', g.vo)
    Wpvo += -1.0*einsum('aj,Iji->Iai', T1, g.oo)
    Wpvo += 1.0*einsum('bi,Iab->Iai', T1, g.vv)
    Wpvo += -1.0*einsum('abji,Ijb->Iai', T2, g.ov)
    Wpvo += -1.0*einsum('bi,aj,Ijb->Iai', T1, T1, g.ov)

    Wp_ov = numpy.zeros((nm,no,nv))
    Wp_ov += 1.0*einsum('Iia->Iia', h.ov)
    Wp_ov += -1.0*einsum('Ibj,jiab->Iia', U11, I.oovv)

    Wp_vv = numpy.zeros((nm,nv,nv))
    Wp_vv += 1.0*einsum('Iab->Iab', h.vv)
    Wp_vv += -1.0*einsum('Iai,ib->Iab', U11, F.ov)
    Wp_vv += -1.0*einsum('ai,Iib->Iab', T1, h.ov)
    Wp_vv += 1.0*einsum('Ici,aibc->Iab', U11, I.vovv)
    Wp_vv += -1.0*einsum('J,Iai,Jib->Iab', S1, U11, g.ov)
    Wp_vv += -1.0*einsum('ai,Icj,ijbc->Iab', T1, U11, I.oovv)
    Wp_vv += 1.0*einsum('ci,Iaj,ijbc->Iab', T1, U11, I.oovv)

    Wp_oo = numpy.zeros((nm,no,no))
    Wp_oo += 1.0*einsum('Iji->Iji', h.oo)
    Wp_oo += 1.0*einsum('Iai,ja->Iji', U11, F.ov)
    Wp_oo += 1.0*einsum('ai,Ija->Iji', T1, h.ov)
    Wp_oo += -1.0*einsum('Iak,kjia->Iji', U11, I.ooov)
    Wp_oo += 1.0*einsum('J,Iai,Jja->Iji', S1, U11, g.ov)
    Wp_oo += 1.0*einsum('ai,Ibk,kjba->Iji', T1, U11, I.oovv)
    Wp_oo += -1.0*einsum('ak,Ibi,kjba->Iji', T1, U11, I.oovv)

    Wpvvoo = numpy.zeros((nm,nv,nv,no,no))
    Wpvvoo += 1.0*einsum('bakj,Iki->Iabij', T2, g.oo)
    Wpvvoo += -1.0*einsum('baki,Ikj->Iabij', T2, g.oo)
    Wpvvoo += -1.0*einsum('acji,Ibc->Iabij', T2, g.vv)
    Wpvvoo += 1.0*einsum('bcji,Iac->Iabij', T2, g.vv)
    Wpvvoo += 1.0*einsum('ci,bakj,Ikc->Iabij', T1, T2, g.ov)
    Wpvvoo += -1.0*einsum('cj,baki,Ikc->Iabij', T1, T2, g.ov)
    Wpvvoo += 1.0*einsum('bk,acji,Ikc->Iabij', T1, T2, g.ov)
    Wpvvoo += -1.0*einsum('ak,bcji,Ikc->Iabij', T1, T2, g.ov)

    Wpvvov = numpy.zeros((nm,nv,nv,no,nv))
    Wpvvov += -1.0*einsum('baji,Ijc->Iabic', T2, g.ov)

    Wpvooo = numpy.zeros((nm,nv,no,no,no))
    Wpvooo += -1.0*einsum('abkj,Iib->Iaijk', T2, g.ov)

    Wp_vovo = numpy.zeros((nm,nv,no,nv,no))
    Wp_vovo += 1.0*einsum('Iak,kijb->Iaibj', U11, I.ooov)
    Wp_vovo += 1.0*einsum('Icj,aibc->Iaibj', U11, I.vovv)
    Wp_vovo += -1.0*einsum('cj,Iak,kibc->Iaibj', T1, U11, I.oovv)
    Wp_vovo += -1.0*einsum('ak,Icj,kibc->Iaibj', T1, U11, I.oovv)

    Wp_ovvv = numpy.zeros((nm,no,nv,nv,nv))
    Wp_ovvv += -1.0*einsum('Iaj,jicb->Iiabc', U11, I.oovv)

    Wp_oovo = numpy.zeros((nm,no,no,nv,no))
    Wp_oovo += -1.0*einsum('Ibk,jiab->Iijak', U11, I.oovv)

    Wp_pvo = numpy.zeros((nm,nm,nv,no))
    Wp_pvo += -1.0*einsum('Iaj,Jji->IJai', U11, g.oo)
    Wp_pvo += 1.0*einsum('Ibi,Jab->IJai', U11, g.vv)
    Wp_pvo += -1.0*einsum('bi,Iaj,Jjb->IJai', T1, U11, g.ov)
    Wp_pvo += -1.0*einsum('aj,Ibi,Jjb->IJai', T1, U11, g.ov)

    Wp_pvv = numpy.zeros((nm,nm,nv,nv))
    Wp_pvv += -1.0*einsum('Iai,Jib->IJab', U11, g.ov)

    Wp_poo = numpy.zeros((nm,nm,no,no))
    Wp_poo += 1.0*einsum('Iaj,Jia->IJij', U11, g.ov)

    sigS = numpy.zeros(T1.shape)
    sigD = numpy.zeros(T2.shape)
    sig1 = numpy.zeros(S1.shape)
    sigS1 = numpy.zeros(U11.shape)

    sigS += -1.0*einsum('ji,aj->ai', Woo, RS)
    sigS += 1.0*einsum('ab,bi->ai', Wvv, RS)
    sigS += 1.0*einsum('I,Iai->ai', Wp, RS1)
    sigS += 1.0*einsum('Iai,I->ai', Wpvo, R1)
    sigS += -1.0*einsum('jb,abji->ai', Wov, RD)
    sigS += 1.0*einsum('ajib,bj->ai', Wvoov, RS)
    sigS += -1.0*einsum('Iji,Iaj->ai', Wpoo, RS1)
    sigS += 1.0*einsum('Iab,Ibi->ai', Wpvv, RS1)
    sigS += 0.5*einsum('jkib,abkj->ai', Wooov, RD)
    sigS += 0.5*einsum('ajbc,cbji->ai', Wvovv, RD)

    sigD += 1.0*einsum('ki,bakj->abij', Woo, RD)
    sigD += -1.0*einsum('kj,baki->abij', Woo, RD)
    sigD += -1.0*einsum('bc,acji->abij', Wvv, RD)
    sigD += 1.0*einsum('ac,bcji->abij', Wvv, RD)
    sigD += 1.0*einsum('kbji,ak->abij', Wovoo, RS)
    sigD += -1.0*einsum('kaji,bk->abij', Wovoo, RS)
    sigD += 1.0*einsum('baci,cj->abij', Wvvvo, RS)
    sigD += -1.0*einsum('bacj,ci->abij', Wvvvo, RS)
    sigD += -1.0*einsum('Ibi,Iaj->abij', Wpvo, RS1)
    sigD += 1.0*einsum('Iai,Ibj->abij', Wpvo, RS1)
    sigD += 1.0*einsum('Ibj,Iai->abij', Wpvo, RS1)
    sigD += -1.0*einsum('Iaj,Ibi->abij', Wpvo, RS1)
    sigD += -0.5*einsum('klji,balk->abij', Woooo, RD)
    sigD += 1.0*einsum('bkic,ackj->abij', Wvoov, RD)
    sigD += -1.0*einsum('akic,bckj->abij', Wvoov, RD)
    sigD += -1.0*einsum('bkjc,acki->abij', Wvoov, RD)
    sigD += 1.0*einsum('akjc,bcki->abij', Wvoov, RD)
    sigD += -0.5*einsum('bacd,dcji->abij', Wvvvv, RD)

    sigD += 1.0*einsum('Iabij,I->abij', Wpvvoo, R1)
    sigD += 1.0*einsum('labdij,dl->abij', Wovvvoo, RS)
    sigD += 1.0*einsum('Iabic,Icj->abij', Wpvvov, RS1)
    sigD += -1.0*einsum('Iabjc,Ici->abij', Wpvvov, RS1)
    sigD += -1.0*einsum('Iakij,Ibk->abij', Wpvooo, RS1)
    sigD += +1.0*einsum('Ibkij,Iak->abij', Wpvooo, RS1)
    sigD += 0.5*einsum('albcdj,cdil->abij', Wvovvvo, RD)
    sigD += -0.5*einsum('albcdi,cdjl->abij', Wvovvvo, RD)
    sigD += -0.5*einsum('klbidj,adkl->abij', Woovovo, RD)
    sigD += 0.5*einsum('klaidj,bdkl->abij', Woovovo, RD)

    sig1 += 1.0*einsum('IJ,J->I', Wp_p, R1)
    sig1 += 1.0*einsum('ia,Iai->I', Wov, RS1)
    sig1 += 1.0*einsum('Iia,ai->I', Wp_ov, RS)

    sigS1 += -1.0*einsum('ji,Iaj->Iai', Woo, RS1)
    sigS1 += 1.0*einsum('ab,Ibi->Iai', Wvv, RS1)
    sigS1 += 1.0*einsum('IJ,Jai->Iai', Wp_p, RS1)
    sigS1 += -1.0*einsum('Iji,aj->Iai', Wp_oo, RS)
    sigS1 += 1.0*einsum('Iab,bi->Iai', Wp_vv, RS)
    sigS1 += 1.0*einsum('ajib,Ibj->Iai', Wvoov, RS1)
    sigS1 += -1.0*einsum('Ijb,abji->Iai', Wp_ov, RD)

    sigS1 += einsum('IJab,Jbi->Iai', Wp_pvv, RS1)
    sigS1 -= einsum('IJji,Jaj->Iai', Wp_poo, RS1)
    sigS1 -= einsum('Iajbi,bj->Iai',Wp_vovo, RS)
    sigS1 += 0.5*einsum('Ijabc,bcji->Iai',Wp_ovvv, RD)
    sigS1 -= 0.5*einsum('Ijkbi,bajk->Iai',Wp_oovo, RD)
    sigS1 += einsum('IJai,J->Iai',Wp_pvo, R1)

    return sigS, sigD, sig1, sigS1

def eom_ip_epccsd_1_s1_sigma_slow(RS, RD, RS1, amps, F, I, w, g, h, G, H):
    T1,T2,S1,U11 = amps
    nv,no = T1.shape
    nm = S1.shape[0]

    sigS = numpy.zeros((no))
    sigD = numpy.zeros((nv,no,no))
    sigS1 = numpy.zeros((nm,no))

    sigS += -1.0*einsum('ji,j->i', F.oo, RS)
    sigS += 1.0*einsum('I,Ii->i', G, RS1)
    sigS += -1.0*einsum('ja,aji->i', F.ov, RD)
    sigS += -1.0*einsum('Iji,Ij->i', g.oo, RS1)
    sigS += 0.5*einsum('jkia,akj->i', I.ooov, RD)
    sigS += -1.0*einsum('ja,ai,j->i', F.ov, T1, RS)
    sigS += -1.0*einsum('Iji,I,j->i', g.oo, S1, RS)
    sigS += 1.0*einsum('jkia,aj,k->i', I.ooov, T1, RS)
    sigS += -1.0*einsum('Ija,ai,Ij->i', g.ov, T1, RS1)
    sigS += 1.0*einsum('Ija,aj,Ii->i', g.ov, T1, RS1)
    sigS += -1.0*einsum('Ija,I,aji->i', g.ov, S1, RD)
    sigS += -1.0*einsum('Ija,Iai,j->i', g.ov, U11, RS)
    sigS += -0.5*einsum('jkab,bi,akj->i', I.oovv, T1, RD)
    sigS += 1.0*einsum('jkab,bj,aki->i', I.oovv, T1, RD)
    sigS += 0.5*einsum('jkab,baji,k->i', I.oovv, T2, RS)
    sigS += -1.0*einsum('Ija,ai,I,j->i', g.ov, T1, S1, RS)
    sigS += -1.0*einsum('jkab,bi,aj,k->i', I.oovv, T1, T1, RS)

    sigD += -1.0*einsum('ki,akj->aij', F.oo, RD)
    sigD += 1.0*einsum('kj,aki->aij', F.oo, RD)
    sigD += -1.0*einsum('ab,bji->aij', F.vv, RD)
    sigD += -1.0*einsum('akji,k->aij', I.vooo, RS)
    sigD += -1.0*einsum('Iai,Ij->aij', g.vo, RS1)
    sigD += 1.0*einsum('Iaj,Ii->aij', g.vo, RS1)
    sigD += 0.5*einsum('klji,alk->aij', I.oooo, RD)
    sigD += -1.0*einsum('akbi,bkj->aij', I.vovo, RD)
    sigD += 1.0*einsum('akbj,bki->aij', I.vovo, RD)
    sigD += -1.0*einsum('kb,bi,akj->aij', F.ov, T1, RD)
    sigD += 1.0*einsum('kb,bj,aki->aij', F.ov, T1, RD)
    sigD += 1.0*einsum('kb,ak,bji->aij', F.ov, T1, RD)
    sigD += -1.0*einsum('kb,abji,k->aij', F.ov, T2, RS)
    sigD += 1.0*einsum('klji,ak,l->aij', I.oooo, T1, RS)
    sigD += -1.0*einsum('akbi,bj,k->aij', I.vovo, T1, RS)
    sigD += 1.0*einsum('akbj,bi,k->aij', I.vovo, T1, RS)
    sigD += 1.0*einsum('Iki,ak,Ij->aij', g.oo, T1, RS1)
    sigD += -1.0*einsum('Ikj,ak,Ii->aij', g.oo, T1, RS1)
    sigD += -1.0*einsum('Iki,I,akj->aij', g.oo, S1, RD)
    sigD += 1.0*einsum('Ikj,I,aki->aij', g.oo, S1, RD)
    sigD += -1.0*einsum('Iki,Iaj,k->aij', g.oo, U11, RS)
    sigD += 1.0*einsum('Ikj,Iai,k->aij', g.oo, U11, RS)
    sigD += -1.0*einsum('Iab,bi,Ij->aij', g.vv, T1, RS1)
    sigD += 1.0*einsum('Iab,bj,Ii->aij', g.vv, T1, RS1)
    sigD += -1.0*einsum('Iab,I,bji->aij', g.vv, S1, RD)
    sigD += -0.5*einsum('klib,bj,alk->aij', I.ooov, T1, RD)
    sigD += -1.0*einsum('klib,ak,blj->aij', I.ooov, T1, RD)
    sigD += 1.0*einsum('klib,bk,alj->aij', I.ooov, T1, RD)
    sigD += 0.5*einsum('kljb,bi,alk->aij', I.ooov, T1, RD)
    sigD += 1.0*einsum('kljb,ak,bli->aij', I.ooov, T1, RD)
    sigD += -1.0*einsum('kljb,bk,ali->aij', I.ooov, T1, RD)
    sigD += -1.0*einsum('klib,abkj,l->aij', I.ooov, T2, RS)
    sigD += 1.0*einsum('kljb,abki,l->aij', I.ooov, T2, RS)
    sigD += -1.0*einsum('akbc,ci,bkj->aij', I.vovv, T1, RD)
    sigD += 1.0*einsum('akbc,cj,bki->aij', I.vovv, T1, RD)
    sigD += -1.0*einsum('akbc,ck,bji->aij', I.vovv, T1, RD)
    sigD += 0.5*einsum('akbc,cbji,k->aij', I.vovv, T2, RS)
    sigD += -1.0*einsum('Ikb,abji,Ik->aij', g.ov, T2, RS1)
    sigD += 1.0*einsum('Ikb,abki,Ij->aij', g.ov, T2, RS1)
    sigD += -1.0*einsum('Ikb,abkj,Ii->aij', g.ov, T2, RS1)
    sigD += 1.0*einsum('Ikb,Iai,bkj->aij', g.ov, U11, RD)
    sigD += -1.0*einsum('Ikb,Ibi,akj->aij', g.ov, U11, RD)
    sigD += -1.0*einsum('Ikb,Iaj,bki->aij', g.ov, U11, RD)
    sigD += 1.0*einsum('Ikb,Ibj,aki->aij', g.ov, U11, RD)
    sigD += 1.0*einsum('Ikb,Iak,bji->aij', g.ov, U11, RD)
    sigD += -0.5*einsum('klbc,acji,blk->aij', I.oovv, T2, RD)
    sigD += -0.25*einsum('klbc,cbji,alk->aij', I.oovv, T2, RD)
    sigD += 1.0*einsum('klbc,acki,blj->aij', I.oovv, T2, RD)
    sigD += 0.5*einsum('klbc,cbki,alj->aij', I.oovv, T2, RD)
    sigD += -1.0*einsum('klbc,ackj,bli->aij', I.oovv, T2, RD)
    sigD += -0.5*einsum('klbc,cbkj,ali->aij', I.oovv, T2, RD)
    sigD += -0.5*einsum('klbc,aclk,bji->aij', I.oovv, T2, RD)
    sigD += -1.0*einsum('klib,bj,ak,l->aij', I.ooov, T1, T1, RS)
    sigD += 1.0*einsum('kljb,bi,ak,l->aij', I.ooov, T1, T1, RS)
    sigD += -1.0*einsum('akbc,ci,bj,k->aij', I.vovv, T1, T1, RS)
    sigD += 1.0*einsum('Ikb,bi,ak,Ij->aij', g.ov, T1, T1, RS1)
    sigD += -1.0*einsum('Ikb,bj,ak,Ii->aij', g.ov, T1, T1, RS1)
    sigD += -1.0*einsum('Ikb,bi,I,akj->aij', g.ov, T1, S1, RD)
    sigD += 1.0*einsum('Ikb,bj,I,aki->aij', g.ov, T1, S1, RD)
    sigD += 1.0*einsum('Ikb,ak,I,bji->aij', g.ov, T1, S1, RD)
    sigD += -1.0*einsum('Ikb,bi,Iaj,k->aij', g.ov, T1, U11, RS)
    sigD += 1.0*einsum('Ikb,bj,Iai,k->aij', g.ov, T1, U11, RS)
    sigD += -1.0*einsum('Ikb,abji,I,k->aij', g.ov, T2, S1, RS)
    sigD += 0.5*einsum('klbc,ci,bj,alk->aij', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('klbc,ci,ak,blj->aij', I.oovv, T1, T1, RD)
    sigD += -1.0*einsum('klbc,ci,bk,alj->aij', I.oovv, T1, T1, RD)
    sigD += -1.0*einsum('klbc,cj,ak,bli->aij', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('klbc,cj,bk,ali->aij', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('klbc,ak,cl,bji->aij', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('klbc,ci,abkj,l->aij', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('klbc,cj,abki,l->aij', I.oovv, T1, T2, RS)
    sigD += -0.5*einsum('klbc,ak,cbji,l->aij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klbc,ck,abji,l->aij', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('klbc,ci,bj,ak,l->aij', I.oovv, T1, T1, T1, RS)

    sigS1 += -1.0*einsum('ji,Ij->Ii', F.oo, RS1)
    sigS1 += 1.0*einsum('I,Ii->Ii', w, RS1)
    sigS1 += -1.0*einsum('Iji,j->Ii', h.oo, RS)
    sigS1 += -1.0*einsum('Ija,aji->Ii', h.ov, RD)
    sigS1 += -1.0*einsum('ja,ai,Ij->Ii', F.ov, T1, RS1)
    sigS1 += -1.0*einsum('ja,Iai,j->Ii', F.ov, U11, RS)
    sigS1 += -1.0*einsum('Jji,J,Ij->Ii', g.oo, S1, RS1)
    sigS1 += -1.0*einsum('Ija,ai,j->Ii', h.ov, T1, RS)
    sigS1 += 1.0*einsum('jkia,aj,Ik->Ii', I.ooov, T1, RS1)
    sigS1 += 1.0*einsum('jkia,Iaj,k->Ii', I.ooov, U11, RS)
    sigS1 += -1.0*einsum('Jja,Iai,Jj->Ii', g.ov, U11, RS1)
    sigS1 += 1.0*einsum('Jja,Iaj,Ji->Ii', g.ov, U11, RS1)
    sigS1 += -1.0*einsum('Jja,Jai,Ij->Ii', g.ov, U11, RS1)
    sigS1 += 0.5*einsum('jkab,baji,Ik->Ii', I.oovv, T2, RS1)
    sigS1 += -0.5*einsum('jkab,Ibi,akj->Ii', I.oovv, U11, RD)
    sigS1 += 1.0*einsum('jkab,Ibj,aki->Ii', I.oovv, U11, RD)
    sigS1 += -1.0*einsum('Jja,ai,J,Ij->Ii', g.ov, T1, S1, RS1)
    sigS1 += -1.0*einsum('Jja,J,Iai,j->Ii', g.ov, S1, U11, RS)
    sigS1 += -1.0*einsum('jkab,bi,aj,Ik->Ii', I.oovv, T1, T1, RS1)
    sigS1 += -1.0*einsum('jkab,bi,Iaj,k->Ii', I.oovv, T1, U11, RS)
    sigS1 += 1.0*einsum('jkab,bj,Iai,k->Ii', I.oovv, T1, U11, RS)

    return sigS, sigD, sigS1

def eom_ip_epccsd_1_s1_sigma_int(RS, RD, RS1, amps, F, I, w, g, h, G, H):
    T1,T2,S1,U11 = amps
    nv,no = T1.shape
    nm = S1.shape[0]

    sigS = numpy.zeros((no))
    sigD = numpy.zeros((nv,no,no))
    sigS1 = numpy.zeros((nm,no))

    Wov = numpy.zeros((no,nv))
    Wov += 1.0*einsum('ia->ia', F.ov)
    Wov += 1.0*einsum('I,Iia->ia', S1, g.ov)
    Wov += -1.0*einsum('bj,jiab->ia', T1, I.oovv)

    Woo = numpy.zeros((no,no))
    Woo += 1.0*einsum('ij->ij', F.oo)
    Woo += 1.0*einsum('aj,ia->ij', T1, F.ov)
    Woo += 1.0*einsum('I,Iij->ij', S1, g.oo)
    Woo += -1.0*einsum('ak,kija->ij', T1, I.ooov)
    Woo += 1.0*einsum('Iaj,Iia->ij', U11, g.ov)
    Woo += -0.5*einsum('abkj,kiba->ij', T2, I.oovv)
    Woo += 1.0*einsum('aj,I,Iia->ij', T1, S1, g.ov)
    Woo += 1.0*einsum('aj,bk,kiba->ij', T1, T1, I.oovv)

    Wvv = numpy.zeros((nv,nv))
    Wvv += 1.0*einsum('ab->ab', F.vv)
    Wvv += -1.0*einsum('ai,ib->ab', T1, F.ov)
    Wvv += 1.0*einsum('I,Iab->ab', S1, g.vv)
    Wvv += 1.0*einsum('ci,aibc->ab', T1, I.vovv)
    Wvv += -1.0*einsum('Iai,Iib->ab', U11, g.ov)
    Wvv += 0.5*einsum('acij,jibc->ab', T2, I.oovv)
    Wvv += -1.0*einsum('ai,I,Iib->ab', T1, S1, g.ov)
    Wvv += -1.0*einsum('ai,cj,ijbc->ab', T1, T1, I.oovv)

    Woooo = numpy.zeros((no,no,no,no))
    Woooo += 1.0*einsum('jilk->ijkl', I.oooo)
    Woooo += -1.0*einsum('al,jika->ijkl', T1, I.ooov)
    Woooo += 1.0*einsum('ak,jila->ijkl', T1, I.ooov)
    Woooo += -0.5*einsum('ablk,jiba->ijkl', T2, I.oovv)
    Woooo += 1.0*einsum('ak,bl,jiba->ijkl', T1, T1, I.oovv)

    Wooov = numpy.zeros((no,no,no,nv))
    Wooov += -1.0*einsum('jika->ijka', I.ooov)
    Wooov += 1.0*einsum('bk,jiab->ijka', T1, I.oovv)

    Wvoov = numpy.zeros((nv,no,no,nv))
    Wvoov += -1.0*einsum('aibj->aijb', I.vovo)
    Wvoov += -1.0*einsum('ak,kijb->aijb', T1, I.ooov)
    Wvoov += -1.0*einsum('cj,aibc->aijb', T1, I.vovv)
    Wvoov += 1.0*einsum('Iaj,Iib->aijb', U11, g.ov)
    Wvoov += 1.0*einsum('ackj,kibc->aijb', T2, I.oovv)
    Wvoov += 1.0*einsum('cj,ak,kibc->aijb', T1, T1, I.oovv)

    Wovoo = numpy.zeros((no,nv,no,no))
    Wovoo += 1.0*einsum('aikj->iajk', I.vooo)
    Wovoo += 1.0*einsum('abkj,ib->iajk', T2, F.ov)
    Wovoo += -1.0*einsum('al,likj->iajk', T1, I.oooo)
    Wovoo += 1.0*einsum('bk,aibj->iajk', T1, I.vovo)
    Wovoo += -1.0*einsum('bj,aibk->iajk', T1, I.vovo)
    Wovoo += 1.0*einsum('Iak,Iij->iajk', U11, g.oo)
    Wovoo += -1.0*einsum('Iaj,Iik->iajk', U11, g.oo)
    Wovoo += 1.0*einsum('ablk,lijb->iajk', T2, I.ooov)
    Wovoo += -1.0*einsum('ablj,likb->iajk', T2, I.ooov)
    Wovoo += -0.5*einsum('bckj,aicb->iajk', T2, I.vovv)
    Wovoo += 1.0*einsum('bk,al,lijb->iajk', T1, T1, I.ooov)
    Wovoo += -1.0*einsum('bj,al,likb->iajk', T1, T1, I.ooov)
    Wovoo += 1.0*einsum('bj,ck,aicb->iajk', T1, T1, I.vovv)
    Wovoo += 1.0*einsum('bj,Iak,Iib->iajk', T1, U11, g.ov)
    Wovoo += -1.0*einsum('bk,Iaj,Iib->iajk', T1, U11, g.ov)
    Wovoo += 1.0*einsum('abkj,I,Iib->iajk', T2, S1, g.ov)
    Wovoo += -1.0*einsum('bj,aclk,licb->iajk', T1, T2, I.oovv)
    Wovoo += 1.0*einsum('bk,aclj,licb->iajk', T1, T2, I.oovv)
    Wovoo += 0.5*einsum('al,bckj,licb->iajk', T1, T2, I.oovv)
    Wovoo += -1.0*einsum('bl,ackj,licb->iajk', T1, T2, I.oovv)
    Wovoo += -1.0*einsum('bj,ck,al,licb->iajk', T1, T1, T1, I.oovv)

    Woovovo = numpy.zeros((no,no,nv,no,nv,no))
    Woovovo += 1.0*einsum('acij,klbc->lkajbi', T2, I.oovv)

    Wp = numpy.zeros((nm))
    Wp += 1.0*einsum('I->I', G)
    Wp += 1.0*einsum('ai,Iia->I', T1, g.ov)

    Wpoo = numpy.zeros((nm,no,no))
    Wpoo += 1.0*einsum('Iji->Iji', g.oo)
    Wpoo += 1.0*einsum('ai,Ija->Iji', T1, g.ov)

    Wpvo = numpy.zeros((nm,nv,no))
    Wpvo += 1.0*einsum('Iai->Iai', g.vo)
    Wpvo += -1.0*einsum('aj,Iji->Iai', T1, g.oo)
    Wpvo += 1.0*einsum('bi,Iab->Iai', T1, g.vv)
    Wpvo += -1.0*einsum('abji,Ijb->Iai', T2, g.ov)
    Wpvo += -1.0*einsum('bi,aj,Ijb->Iai', T1, T1, g.ov)

    Wp_oo = numpy.zeros((nm,no,no))
    Wp_oo += 1.0*einsum('Iji->Iji', h.oo)
    Wp_oo += 1.0*einsum('Iai,ja->Iji', U11, F.ov)
    Wp_oo += 1.0*einsum('ai,Ija->Iji', T1, h.ov)
    Wp_oo += -1.0*einsum('Iak,kjia->Iji', U11, I.ooov)
    Wp_oo += 1.0*einsum('J,Iai,Jja->Iji', S1, U11, g.ov)
    Wp_oo += 1.0*einsum('ai,Ibk,kjba->Iji', T1, U11, I.oovv)
    Wp_oo += -1.0*einsum('ak,Ibi,kjba->Iji', T1, U11, I.oovv)

    Wp_ov = numpy.zeros((nm,no,nv))
    Wp_ov += 1.0*einsum('Iia->Iia', h.ov)
    Wp_ov += -1.0*einsum('Ibj,jiab->Iia', U11, I.oovv)

    Wp_oovo = numpy.zeros((nm,no,no,nv,no))
    Wp_oovo += -1.0*einsum('Ibk,jiab->Iijak', U11, I.oovv)

    Wp_p = numpy.zeros((nm,nm))
    Wp_p += numpy.diag(w)
    Wp_p += 1.0*einsum('Iai,Jia->IJ', U11, g.ov)

    Wp_poo = numpy.zeros((nm,nm,no,no))
    Wp_poo += 1.0*einsum('Iaj,Jia->IJij', U11, g.ov)

    Wpvooo = numpy.zeros((nm,nv,no,no,no))
    Wpvooo += -1.0*einsum('abkj,Iib->Iaijk', T2, g.ov)

    sigS += -1.0*einsum('ji,j->i', Woo, RS)
    sigS += 1.0*einsum('I,Ii->i', Wp, RS1)
    sigS += -1.0*einsum('ja,aji->i', Wov, RD)
    sigS += -1.0*einsum('Iji,Ij->i', Wpoo, RS1)
    sigS += 0.5*einsum('jkia,akj->i', Wooov, RD)

    sigD += -1.0*einsum('ki,akj->aij', Woo, RD)
    sigD += 1.0*einsum('kj,aki->aij', Woo, RD)
    sigD += -1.0*einsum('ab,bji->aij', Wvv, RD)
    sigD += 1.0*einsum('kaji,k->aij', Wovoo, RS)
    sigD += -1.0*einsum('Iai,Ij->aij', Wpvo, RS1)
    sigD += 1.0*einsum('Iaj,Ii->aij', Wpvo, RS1)
    sigD += 0.5*einsum('klji,alk->aij', Woooo, RD)
    sigD += 1.0*einsum('akib,bkj->aij', Wvoov, RD)
    sigD += -1.0*einsum('akjb,bki->aij', Wvoov, RD)

    sigD += 1.0*einsum('Iakij,Ik->aij',Wpvooo, RS1)
    sigD += 0.5*einsum('lkajbi,blk->aij',Woovovo, RD)

    sigS1 += -1.0*einsum('ji,Ij->Ii', Woo, RS1)
    sigS1 += 1.0*einsum('IJ,Ji->Ii', Wp_p, RS1)
    sigS1 += -1.0*einsum('Iji,j->Ii', Wp_oo, RS)
    sigS1 += -1.0*einsum('Ija,aji->Ii', Wp_ov, RD)

    sigS1 += 0.5*einsum('Ijkbi,bjk->Ii', Wp_oovo, RD)
    sigS1 += -einsum('IJji,Jj->Ii', Wp_poo, RS1)

    return sigS, sigD, sigS1

def eom_ea_epccsd_1_s1_sigma_slow(RS, RD, RS1, amps, F, I, w, g, h, G, H):
    T1,T2,S1,U11 = amps
    nv,no = T1.shape
    nm = S1.shape[0]

    sigS = numpy.zeros((nv))
    sigD = numpy.zeros((nv,nv,no))
    sigS1 = numpy.zeros((nm,nv))

    sigS += 1.0*einsum('ab,b->a', F.vv, RS)
    sigS += 1.0*einsum('I,Ia->a', G, RS1)
    sigS += 1.0*einsum('ib,abi->a', F.ov, RD)
    sigS += 1.0*einsum('Iab,Ib->a', g.vv, RS1)
    sigS += -0.5*einsum('aibc,cbi->a', I.vovv, RD)
    sigS += -1.0*einsum('ib,ai,b->a', F.ov, T1, RS)
    sigS += 1.0*einsum('Iab,I,b->a', g.vv, S1, RS)
    sigS += 1.0*einsum('aibc,ci,b->a', I.vovv, T1, RS)
    sigS += -1.0*einsum('Iib,ai,Ib->a', g.ov, T1, RS1)
    sigS += 1.0*einsum('Iib,bi,Ia->a', g.ov, T1, RS1)
    sigS += 1.0*einsum('Iib,I,abi->a', g.ov, S1, RD)
    sigS += -1.0*einsum('Iib,Iai,b->a', g.ov, U11, RS)
    sigS += 0.5*einsum('ijbc,ai,cbj->a', I.oovv, T1, RD)
    sigS += -1.0*einsum('ijbc,ci,abj->a', I.oovv, T1, RD)
    sigS += 0.5*einsum('ijbc,acji,b->a', I.oovv, T2, RS)
    sigS += -1.0*einsum('Iib,ai,I,b->a', g.ov, T1, S1, RS)
    sigS += -1.0*einsum('ijbc,ai,cj,b->a', I.oovv, T1, T1, RS)

    sigD += 1.0*einsum('ji,baj->abi', F.oo, RD)
    sigD += 1.0*einsum('bc,aci->abi', F.vv, RD)
    sigD += -1.0*einsum('ac,bci->abi', F.vv, RD)
    sigD += -1.0*einsum('baci,c->abi', I.vvvo, RS)
    sigD += 1.0*einsum('Ibi,Ia->abi', g.vo, RS1)
    sigD += -1.0*einsum('Iai,Ib->abi', g.vo, RS1)
    sigD += -1.0*einsum('bjci,acj->abi', I.vovo, RD)
    sigD += 1.0*einsum('ajci,bcj->abi', I.vovo, RD)
    sigD += 0.5*einsum('bacd,dci->abi', I.vvvv, RD)
    sigD += 1.0*einsum('jc,ci,baj->abi', F.ov, T1, RD)
    sigD += -1.0*einsum('jc,bj,aci->abi', F.ov, T1, RD)
    sigD += 1.0*einsum('jc,aj,bci->abi', F.ov, T1, RD)
    sigD += 1.0*einsum('jc,baji,c->abi', F.ov, T2, RS)
    sigD += 1.0*einsum('bjci,aj,c->abi', I.vovo, T1, RS)
    sigD += -1.0*einsum('ajci,bj,c->abi', I.vovo, T1, RS)
    sigD += -1.0*einsum('bacd,di,c->abi', I.vvvv, T1, RS)
    sigD += -1.0*einsum('Iji,bj,Ia->abi', g.oo, T1, RS1)
    sigD += 1.0*einsum('Iji,aj,Ib->abi', g.oo, T1, RS1)
    sigD += 1.0*einsum('Iji,I,baj->abi', g.oo, S1, RD)
    sigD += 1.0*einsum('Ibc,ci,Ia->abi', g.vv, T1, RS1)
    sigD += -1.0*einsum('Iac,ci,Ib->abi', g.vv, T1, RS1)
    sigD += 1.0*einsum('Ibc,I,aci->abi', g.vv, S1, RD)
    sigD += -1.0*einsum('Iac,I,bci->abi', g.vv, S1, RD)
    sigD += -1.0*einsum('Ibc,Iai,c->abi', g.vv, U11, RS)
    sigD += 1.0*einsum('Iac,Ibi,c->abi', g.vv, U11, RS)
    sigD += -1.0*einsum('jkic,bj,ack->abi', I.ooov, T1, RD)
    sigD += 1.0*einsum('jkic,aj,bck->abi', I.ooov, T1, RD)
    sigD += -1.0*einsum('jkic,cj,bak->abi', I.ooov, T1, RD)
    sigD += -0.5*einsum('jkic,bakj,c->abi', I.ooov, T2, RS)
    sigD += -1.0*einsum('bjcd,di,acj->abi', I.vovv, T1, RD)
    sigD += 1.0*einsum('ajcd,di,bcj->abi', I.vovv, T1, RD)
    sigD += -0.5*einsum('bjcd,aj,dci->abi', I.vovv, T1, RD)
    sigD += 1.0*einsum('bjcd,dj,aci->abi', I.vovv, T1, RD)
    sigD += 0.5*einsum('ajcd,bj,dci->abi', I.vovv, T1, RD)
    sigD += -1.0*einsum('ajcd,dj,bci->abi', I.vovv, T1, RD)
    sigD += 1.0*einsum('bjcd,adji,c->abi', I.vovv, T2, RS)
    sigD += -1.0*einsum('ajcd,bdji,c->abi', I.vovv, T2, RS)
    sigD += 1.0*einsum('Ijc,baji,Ic->abi', g.ov, T2, RS1)
    sigD += -1.0*einsum('Ijc,bcji,Ia->abi', g.ov, T2, RS1)
    sigD += 1.0*einsum('Ijc,acji,Ib->abi', g.ov, T2, RS1)
    sigD += 1.0*einsum('Ijc,Ibi,acj->abi', g.ov, U11, RD)
    sigD += -1.0*einsum('Ijc,Iai,bcj->abi', g.ov, U11, RD)
    sigD += 1.0*einsum('Ijc,Ici,baj->abi', g.ov, U11, RD)
    sigD += -1.0*einsum('Ijc,Ibj,aci->abi', g.ov, U11, RD)
    sigD += 1.0*einsum('Ijc,Iaj,bci->abi', g.ov, U11, RD)
    sigD += -0.5*einsum('jkcd,baji,dck->abi', I.oovv, T2, RD)
    sigD += 1.0*einsum('jkcd,bdji,ack->abi', I.oovv, T2, RD)
    sigD += -1.0*einsum('jkcd,adji,bck->abi', I.oovv, T2, RD)
    sigD += -0.5*einsum('jkcd,dcji,bak->abi', I.oovv, T2, RD)
    sigD += -0.25*einsum('jkcd,bakj,dci->abi', I.oovv, T2, RD)
    sigD += 0.5*einsum('jkcd,bdkj,aci->abi', I.oovv, T2, RD)
    sigD += -0.5*einsum('jkcd,adkj,bci->abi', I.oovv, T2, RD)
    sigD += 1.0*einsum('jkic,bj,ak,c->abi', I.ooov, T1, T1, RS)
    sigD += 1.0*einsum('bjcd,di,aj,c->abi', I.vovv, T1, T1, RS)
    sigD += -1.0*einsum('ajcd,di,bj,c->abi', I.vovv, T1, T1, RS)
    sigD += -1.0*einsum('Ijc,ci,bj,Ia->abi', g.ov, T1, T1, RS1)
    sigD += 1.0*einsum('Ijc,ci,aj,Ib->abi', g.ov, T1, T1, RS1)
    sigD += 1.0*einsum('Ijc,ci,I,baj->abi', g.ov, T1, S1, RD)
    sigD += -1.0*einsum('Ijc,bj,I,aci->abi', g.ov, T1, S1, RD)
    sigD += 1.0*einsum('Ijc,aj,I,bci->abi', g.ov, T1, S1, RD)
    sigD += 1.0*einsum('Ijc,bj,Iai,c->abi', g.ov, T1, U11, RS)
    sigD += -1.0*einsum('Ijc,aj,Ibi,c->abi', g.ov, T1, U11, RS)
    sigD += 1.0*einsum('Ijc,baji,I,c->abi', g.ov, T2, S1, RS)
    sigD += 1.0*einsum('jkcd,di,bj,ack->abi', I.oovv, T1, T1, RD)
    sigD += -1.0*einsum('jkcd,di,aj,bck->abi', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('jkcd,di,cj,bak->abi', I.oovv, T1, T1, RD)
    sigD += 0.5*einsum('jkcd,bj,ak,dci->abi', I.oovv, T1, T1, RD)
    sigD += -1.0*einsum('jkcd,bj,dk,aci->abi', I.oovv, T1, T1, RD)
    sigD += 1.0*einsum('jkcd,aj,dk,bci->abi', I.oovv, T1, T1, RD)
    sigD += 0.5*einsum('jkcd,di,bakj,c->abi', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('jkcd,bj,adki,c->abi', I.oovv, T1, T2, RS)
    sigD += 1.0*einsum('jkcd,aj,bdki,c->abi', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('jkcd,dj,baki,c->abi', I.oovv, T1, T2, RS)
    sigD += -1.0*einsum('jkcd,di,bj,ak,c->abi', I.oovv, T1, T1, T1, RS)

    sigS1 += 1.0*einsum('ab,Ib->Ia', F.vv, RS1)
    sigS1 += 1.0*einsum('I,Ia->Ia', w, RS1)
    sigS1 += 1.0*einsum('Iab,b->Ia', h.vv, RS)
    sigS1 += 1.0*einsum('Iib,abi->Ia', h.ov, RD)
    sigS1 += -1.0*einsum('ib,ai,Ib->Ia', F.ov, T1, RS1)
    sigS1 += -1.0*einsum('ib,Iai,b->Ia', F.ov, U11, RS)
    sigS1 += -1.0*einsum('Iib,ai,b->Ia', h.ov, T1, RS)
    sigS1 += 1.0*einsum('Jab,J,Ib->Ia', g.vv, S1, RS1)
    sigS1 += 1.0*einsum('aibc,ci,Ib->Ia', I.vovv, T1, RS1)
    sigS1 += 1.0*einsum('aibc,Ici,b->Ia', I.vovv, U11, RS)
    sigS1 += -1.0*einsum('Jib,Iai,Jb->Ia', g.ov, U11, RS1)
    sigS1 += 1.0*einsum('Jib,Ibi,Ja->Ia', g.ov, U11, RS1)
    sigS1 += -1.0*einsum('Jib,Jai,Ib->Ia', g.ov, U11, RS1)
    sigS1 += 0.5*einsum('ijbc,acji,Ib->Ia', I.oovv, T2, RS1)
    sigS1 += 0.5*einsum('ijbc,Iai,cbj->Ia', I.oovv, U11, RD)
    sigS1 += -1.0*einsum('ijbc,Ici,abj->Ia', I.oovv, U11, RD)
    sigS1 += -1.0*einsum('Jib,ai,J,Ib->Ia', g.ov, T1, S1, RS1)
    sigS1 += -1.0*einsum('Jib,J,Iai,b->Ia', g.ov, S1, U11, RS)
    sigS1 += -1.0*einsum('ijbc,ai,cj,Ib->Ia', I.oovv, T1, T1, RS1)
    sigS1 += -1.0*einsum('ijbc,ai,Icj,b->Ia', I.oovv, T1, U11, RS)
    sigS1 += 1.0*einsum('ijbc,ci,Iaj,b->Ia', I.oovv, T1, U11, RS)

    return sigS, sigD, sigS1

def eom_ea_epccsd_1_s1_sigma_int(RS, RD, RS1, amps, F, I, w, g, h, G, H):
    T1,T2,S1,U11 = amps
    nv,no = T1.shape
    nm = S1.shape[0]

    sigS = numpy.zeros((nv))
    sigD = numpy.zeros((nv,nv,no))
    sigS1 = numpy.zeros((nm,nv))

    Wov = numpy.zeros((no,nv))
    Wov += 1.0*einsum('ia->ia', F.ov)
    Wov += 1.0*einsum('I,Iia->ia', S1, g.ov)
    Wov += -1.0*einsum('bj,jiab->ia', T1, I.oovv)

    Woo = numpy.zeros((no,no))
    Woo += 1.0*einsum('ij->ij', F.oo)
    Woo += 1.0*einsum('aj,ia->ij', T1, F.ov)
    Woo += 1.0*einsum('I,Iij->ij', S1, g.oo)
    Woo += -1.0*einsum('ak,kija->ij', T1, I.ooov)
    Woo += 1.0*einsum('Iaj,Iia->ij', U11, g.ov)
    Woo += -0.5*einsum('abkj,kiba->ij', T2, I.oovv)
    Woo += 1.0*einsum('aj,I,Iia->ij', T1, S1, g.ov)
    Woo += 1.0*einsum('aj,bk,kiba->ij', T1, T1, I.oovv)

    Wvv = numpy.zeros((nv,nv))
    Wvv += 1.0*einsum('ab->ab', F.vv)
    Wvv += -1.0*einsum('ai,ib->ab', T1, F.ov)
    Wvv += 1.0*einsum('I,Iab->ab', S1, g.vv)
    Wvv += 1.0*einsum('ci,aibc->ab', T1, I.vovv)
    Wvv += -1.0*einsum('Iai,Iib->ab', U11, g.ov)
    Wvv += 0.5*einsum('acij,jibc->ab', T2, I.oovv)
    Wvv += -1.0*einsum('ai,I,Iib->ab', T1, S1, g.ov)
    Wvv += -1.0*einsum('ai,cj,ijbc->ab', T1, T1, I.oovv)

    Wvovv = numpy.zeros((nv,no,nv,nv))
    Wvovv += -1.0*einsum('aicb->aibc', I.vovv)
    Wvovv += 1.0*einsum('aj,jicb->aibc', T1, I.oovv)

    Wvvvo = numpy.zeros((nv,nv,nv,no))
    Wvvvo += -1.0*einsum('baci->abci', I.vvvo)
    Wvvvo += 1.0*einsum('baji,jc->abci', T2, F.ov)
    Wvvvo += 1.0*einsum('aj,bjci->abci', T1, I.vovo)
    Wvvvo += -1.0*einsum('bj,ajci->abci', T1, I.vovo)
    Wvvvo += -1.0*einsum('di,bacd->abci', T1, I.vvvv)
    Wvvvo += -1.0*einsum('Iai,Ibc->abci', U11, g.vv)
    Wvvvo += 1.0*einsum('Ibi,Iac->abci', U11, g.vv)
    Wvvvo += -0.5*einsum('bajk,kjic->abci', T2, I.ooov)
    Wvvvo += 1.0*einsum('adji,bjcd->abci', T2, I.vovv)
    Wvvvo += -1.0*einsum('bdji,ajcd->abci', T2, I.vovv)
    Wvvvo += 1.0*einsum('bj,ak,jkic->abci', T1, T1, I.ooov)
    Wvvvo += 1.0*einsum('di,aj,bjcd->abci', T1, T1, I.vovv)
    Wvvvo += -1.0*einsum('di,bj,ajcd->abci', T1, T1, I.vovv)
    Wvvvo += 1.0*einsum('bj,Iai,Ijc->abci', T1, U11, g.ov)
    Wvvvo += -1.0*einsum('aj,Ibi,Ijc->abci', T1, U11, g.ov)
    Wvvvo += 1.0*einsum('baji,I,Ijc->abci', T2, S1, g.ov)
    Wvvvo += 0.5*einsum('di,bajk,kjcd->abci', T1, T2, I.oovv)
    Wvvvo += -1.0*einsum('bj,adki,jkcd->abci', T1, T2, I.oovv)
    Wvvvo += 1.0*einsum('aj,bdki,jkcd->abci', T1, T2, I.oovv)
    Wvvvo += -1.0*einsum('dj,baki,jkcd->abci', T1, T2, I.oovv)
    Wvvvo += -1.0*einsum('di,bj,ak,jkcd->abci', T1, T1, T1, I.oovv)

    Wvoov = numpy.zeros((nv,no,no,nv))
    Wvoov += -1.0*einsum('aibj->aijb', I.vovo)
    Wvoov += -1.0*einsum('ak,kijb->aijb', T1, I.ooov)
    Wvoov += -1.0*einsum('cj,aibc->aijb', T1, I.vovv)
    Wvoov += 1.0*einsum('Iaj,Iib->aijb', U11, g.ov)
    Wvoov += 1.0*einsum('ackj,kibc->aijb', T2, I.oovv)
    Wvoov += 1.0*einsum('cj,ak,kibc->aijb', T1, T1, I.oovv)

    Wvvvv = numpy.zeros((nv,nv,nv,nv))
    Wvvvv += 1.0*einsum('badc->abcd', I.vvvv)
    Wvvvv += -1.0*einsum('ai,bidc->abcd', T1, I.vovv)
    Wvvvv += 1.0*einsum('bi,aidc->abcd', T1, I.vovv)
    Wvvvv += -0.5*einsum('baij,jidc->abcd', T2, I.oovv)
    Wvvvv += 1.0*einsum('bi,aj,ijdc->abcd', T1, T1, I.oovv)

    Wvovvvo = numpy.zeros((nv,no,nv,nv,nv,no))
    Wvovvvo += -1.0*einsum('bakj,kidc->aibcdj', T2, I.oovv)

    Wpvvov = numpy.zeros((nm,nv,nv,no,nv))
    Wpvvov += -1.0*einsum('baji,Ijc->Iabic', T2, g.ov)

    Wp = numpy.zeros((nm))
    Wp += 1.0*einsum('I->I', G)
    Wp += 1.0*einsum('ai,Iia->I', T1, g.ov)

    Wp_p = numpy.zeros((nm,nm))
    Wp_p += numpy.diag(w)
    Wp_p += 1.0*einsum('Iai,Jia->IJ', U11, g.ov)

    Wp_pvv = numpy.zeros((nm,nm,nv,nv))
    Wp_pvv += -1.0*einsum('Iai,Jib->IJab', U11, g.ov)

    Wpvv = numpy.zeros((nm,nv,nv))
    Wpvv += 1.0*einsum('Iab->Iab', g.vv)
    Wpvv += -1.0*einsum('ai,Iib->Iab', T1, g.ov)

    Wpvo = numpy.zeros((nm,nv,no))
    Wpvo += 1.0*einsum('Iai->Iai', g.vo)
    Wpvo += -1.0*einsum('aj,Iji->Iai', T1, g.oo)
    Wpvo += 1.0*einsum('bi,Iab->Iai', T1, g.vv)
    Wpvo += -1.0*einsum('abji,Ijb->Iai', T2, g.ov)
    Wpvo += -1.0*einsum('bi,aj,Ijb->Iai', T1, T1, g.ov)

    Wp_vv = numpy.zeros((nm,nv,nv))
    Wp_vv += 1.0*einsum('Iab->Iab', h.vv)
    Wp_vv += -1.0*einsum('Iai,ib->Iab', U11, F.ov)
    Wp_vv += -1.0*einsum('ai,Iib->Iab', T1, h.ov)
    Wp_vv += 1.0*einsum('Ici,aibc->Iab', U11, I.vovv)
    Wp_vv += -1.0*einsum('J,Iai,Jib->Iab', S1, U11, g.ov)
    Wp_vv += -1.0*einsum('ai,Icj,ijbc->Iab', T1, U11, I.oovv)
    Wp_vv += 1.0*einsum('ci,Iaj,ijbc->Iab', T1, U11, I.oovv)

    Wp_ov = numpy.zeros((nm,no,nv))
    Wp_ov += 1.0*einsum('Iia->Iia', h.ov)
    Wp_ov += -1.0*einsum('Ibj,jiab->Iia', U11, I.oovv)

    Wp_ovvv = numpy.zeros((nm,no,nv,nv,nv))
    Wp_ovvv += -1.0*einsum('Iaj,jicb->Iiabc', U11, I.oovv)

    sigS += 1.0*einsum('ab,b->a', Wvv, RS)
    sigS += 1.0*einsum('I,Ia->a', Wp, RS1)
    sigS += 1.0*einsum('ib,abi->a', Wov, RD)
    sigS += 1.0*einsum('Iab,Ib->a', Wpvv, RS1)
    sigS += -0.5*einsum('aibc,cbi->a', Wvovv, RD)

    sigD += 1.0*einsum('ji,baj->abi', Woo, RD)
    sigD += 1.0*einsum('bc,aci->abi', Wvv, RD)
    sigD += -1.0*einsum('ac,bci->abi', Wvv, RD)
    sigD += -1.0*einsum('baci,c->abi', Wvvvo, RS)
    sigD += 1.0*einsum('Ibi,Ia->abi', Wpvo, RS1)
    sigD += -1.0*einsum('Iai,Ib->abi', Wpvo, RS1)
    sigD += 1.0*einsum('bjic,acj->abi', Wvoov, RD)
    sigD += -1.0*einsum('ajic,bcj->abi', Wvoov, RD)
    sigD += 0.5*einsum('bacd,dci->abi', Wvvvv, RD)

    sigD += 0.5*einsum('blacdi,dcl->abi', Wvovvvo, RD)
    sigD += -1.0*einsum('Iabic,Ic->abi', Wpvvov, RS1)

    sigS1 += 1.0*einsum('ab,Ib->Ia', Wvv, RS1)
    sigS1 += 1.0*einsum('IJ,Ja->Ia', Wp_p, RS1)
    sigS1 += 1.0*einsum('Iab,b->Ia', Wp_vv, RS)
    sigS1 += 1.0*einsum('Iib,abi->Ia', Wp_ov, RD)

    sigS1 += -0.5*einsum('Ijabc,bcj->Ia', Wp_ovvv, RD)
    sigS1 += 1.0*einsum('IJab,Jb->Ia', Wp_pvv, RS1)

    return sigS, sigD, sigS1
